(function(){
  function $(id){return document.getElementById(id)}
  function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  function arr(v){return Array.isArray(v)?v:[]}
  function ensureStage(){
    var left=$('game-left'); if(!left)return;
    if(!$('lh-side-left'))left.insertAdjacentHTML('beforeend','<aside class="lh-side-panel lh-side-left" id="lh-side-left"></aside><aside class="lh-side-panel lh-side-right" id="lh-side-right"></aside><div class="lh-vn-overlay" id="lh-vn"><div class="lh-vn-box"><button class="lh-vn-close" onclick="closeDialogue()">×</button><div class="lh-vn-speaker" id="lh-vn-speaker"></div><div class="lh-vn-text" id="lh-vn-text"></div><div class="lh-vn-choices" id="lh-vn-choices"></div></div></div>');
    bindCharClick();
  }
  function bindCharClick(){
    var img=$('game-char-img');if(!img)return;
    img.style.cursor='pointer';
    img.onclick=function(e){e.stopPropagation();startDialogue()};
  }
  window.bindCharClick=bindCharClick;
  function chips(title,items){items=arr(items).filter(Boolean);return items.length?'<div class="lh-side-title">'+title+'</div><div class="lh-chip-list">'+items.map(function(x){return'<span class="lh-chip">'+esc(x)+'</span>'}).join('')+'</div>':''}
  function statsHtml(stats){stats=arr(stats).filter(function(x){return x&&x.k});return stats.length?'<div class="lh-side-title">TRPG Stats</div><div class="lh-stat-grid">'+stats.map(function(s){return'<div class="lh-stat"><b>'+esc(s.k)+'</b><span>'+esc(s.v)+'</span></div>'}).join('')+'</div>':''}
  function renderExtra(c){ensureStage();var left=$('lh-side-left'),right=$('lh-side-right');if(!left||!right||!c)return;var profile=Array.isArray(c.profile)?c.profile:[];var essentials=profile.filter(function(p){return /^(나이|성별|신장|체중|체형|생일|혈액형|직업)$/i.test(p.k||'')});var rest=profile.filter(function(p){return !/^(나이|성별|신장|체중|체형|생일|혈액형|직업)$/i.test(p.k||'')});left.innerHTML='<div class="lh-side-title">Basic File</div><table class="game-profile-table">'+(essentials.length?essentials:profile.slice(0,8)).map(function(p){return'<tr><td>'+esc(p.k)+'</td><td>'+esc(p.v)+'</td></tr>'}).join('')+'</table>'+(rest.length?'<div class="lh-side-title" style="margin-top:16px">Notes</div><table class="game-profile-table">'+rest.map(function(p){return'<tr><td>'+esc(p.k)+'</td><td>'+esc(p.v)+'</td></tr>'}).join('')+'</table>':'')+statsHtml(c.stats);right.innerHTML=chips('Keywords',c.keywords)+chips('Like',c.likes)+chips('Hate',c.hates)+chips('Items',c.items)+(c.special?'<div class="lh-side-title" style="margin-top:14px">Special</div><div class="game-desc">'+esc(c.special)+'</div>':'')+(c.hobby?'<div class="lh-side-title" style="margin-top:14px">Hobby / Talent</div><div class="game-desc">'+esc(c.hobby)+'</div>':'');}
  window.renderExtra=renderExtra;
  window.ensureStage=ensureStage;
  var oldOpen=window.openDetail;
  window.openDetail=function(c,auIdx){oldOpen(c,auIdx);setTimeout(function(){renderExtra(c)},0)};
  var dialogueIndex={};
  function buildDialogue(c){dialogueIndex={};arr(c&&c.dialogue).forEach(function(n,i){dialogueIndex[n.id||String(i)]=n});return dialogueIndex;}
  window.startDialogue=function(){if(!window.currentChar)return;ensureStage();var c=window.currentChar,d=buildDialogue(c),keys=Object.keys(d);if(keys.length){showDialogueNode(c.dialogueStart||keys[0]);return}showDialogueNode('__fallback__')}
  window.closeDialogue=function(){var v=$('lh-vn');if(v)v.classList.remove('active')}
  window.showDialogueNode=function(id){ensureStage();var c=window.currentChar,box=$('lh-vn');if(!box||!c)return;if(id==='__fallback__'){box.classList.add('active');$('lh-vn-speaker').textContent=c.name||'';$('lh-vn-text').textContent='...';$('lh-vn-choices').innerHTML='<button class="lh-vn-choice" onclick="closeDialogue()">닫기</button>';return}var node=dialogueIndex[id]||buildDialogue(c)[id];if(!node)return;var img=$('game-char-img');if(node.expression&&img){img.src=node.expression;img.classList.remove('animate-in');void img.offsetWidth;img.classList.add('animate-in')}box.classList.add('active');$('lh-vn-speaker').textContent=node.speaker||(c.name||'');$('lh-vn-text').textContent=node.text||'';var choices=arr(node.choices);$('lh-vn-choices').innerHTML=choices.length?choices.map(function(ch){return'<button class="lh-vn-choice" onclick="showDialogueNode(\''+esc(ch.next||'')+'\')">'+esc(ch.label||'...')+'</button>'}).join(''):'<button class="lh-vn-choice" onclick="closeDialogue()">닫기</button>';}
  function installEditSections(){var panel=$('edit-panel');if(!panel||$('ep-extra-fields'))return;var anchor=$('ep-story');if(!anchor)return;anchor.closest('.section-sep').insertAdjacentHTML('afterend','<div class="section-sep" id="ep-extra-fields"><div class="section-sep-title">특이사항 / 키워드</div><div class="form-group"><label class="form-label">특이사항</label><textarea class="form-input" id="ep-special" rows="2"></textarea></div><div class="form-group"><label class="form-label">취미 / 특기</label><textarea class="form-input" id="ep-hobby" rows="2"></textarea></div><div class="form-group"><label class="form-label">키워드 (,로 구분)</label><input class="form-input" id="ep-keywords"></div><div class="form-row"><div class="form-group"><label class="form-label">Like</label><input class="form-input" id="ep-likes"></div><div class="form-group"><label class="form-label">Hate</label><input class="form-input" id="ep-hates"></div></div><div class="form-group"><label class="form-label">소지품</label><input class="form-input" id="ep-items"></div></div><div class="section-sep"><div class="section-sep-title">TRPG 스테이터스</div><div id="ep-stat-rows"></div><button class="btn-save" style="margin-top:6px;padding:5px 12px;" onclick="addStatRow()">+ 스탯 추가</button></div><div class="section-sep"><div class="section-sep-title">VN 분기 대화</div><div class="lh-line-voice-vol-panel form-group" id="ep-line-voice-vol"><label class="form-label" for="lh-line-voice-vol-range">대사 음성 볼륨 (전체)</label><p class="lh-line-voice-vol-panel__hint">OC·Pair 대사 음성이 재생될 때 공통 적용. 이 기기에만 저장됩니다.</p><div class="lh-line-voice-vol-panel__row"><input id="lh-line-voice-vol-range" type="range" class="lh-line-voice-vol-panel__range" min="0" max="100" step="1" value="85" oninput="(function(r){var v=Number(r.value)/100;try{localStorage.setItem(\'lh_line_voice_volume\',String(v))}catch(e){}var t=r.parentNode.querySelector(\'.lh-line-voice-vol-panel__val\');if(t)t.textContent=r.value+\'%\';if(window.lhSetLineVoiceVol)window.lhSetLineVoiceVol(v)})(this)"><span class="lh-line-voice-vol-panel__val">85%</span></div></div><div style="font-size:10px;color:var(--text-muted);line-height:1.6;margin-bottom:8px;">선택지는 한 줄에 하나씩: 답변|다음ID</div><div id="ep-dialogue-rows"></div><button class="btn-save" style="margin-top:6px;padding:5px 12px;" onclick="addDialogueRow()">+ 대화 노드 추가</button></div>');}
  window.addStatRow=function(k,v){var box=$('ep-stat-rows');if(!box)return;var row=document.createElement('div');row.className='lh-edit-row';row.innerHTML='<div style="display:flex;gap:6px"><input class="form-input stat-key" placeholder="STR / DEX / SAN" value="'+esc(k||'')+'"><input class="form-input stat-val" placeholder="수치" value="'+esc(v||'')+'"><button class="btn-del" onclick="this.closest(\'.lh-edit-row\').remove()">삭제</button></div>';box.appendChild(row)}
  window.addDialogueRow=function(n){n=n||{};var box=$('ep-dialogue-rows');if(!box)return;var choices=arr(n.choices).map(function(c){return (c.label||'')+'|'+(c.next||'')}).join('\n');var row=document.createElement('div');row.className='lh-edit-row';row.innerHTML='<div style="display:grid;grid-template-columns:1fr 1fr;gap:6px"><input class="form-input dlg-id" placeholder="ID 예: start" value="'+esc(n.id||'')+'"><input class="form-input dlg-speaker" placeholder="화자" value="'+esc(n.speaker||'')+'"></div><textarea class="form-input dlg-text" rows="2" placeholder="대사">'+esc(n.text||'')+'</textarea><input class="form-input dlg-expression" placeholder="표정 이미지 URL 또는 파일 data" value="'+esc(n.expression||'')+'"><input class="form-input dlg-voice" placeholder="대사 음성 URL" value="'+esc(n.voice||'')+'"><label class="file-input-label" style="display:inline-block;margin:4px 0;font-size:11px;">음성 파일<input type="file" accept="audio/*" hidden onchange="(function(inp){var f=inp.files&&inp.files[0];if(!f)return;var r=new FileReader();r.onload=function(){var t=inp.closest(\'.lh-edit-row\').querySelector(\'.dlg-voice\');if(t)t.value=r.result};r.readAsDataURL(f);inp.value=\'\'})(this)"></label><textarea class="form-input dlg-choices" rows="2" placeholder="응답|nextId">'+esc(choices)+'</textarea><button class="btn-del" onclick="this.closest(\'.lh-edit-row\').remove()" style="align-self:flex-start">삭제</button>';box.appendChild(row)}
  function csv(id){var e=$(id);return e&&e.value?e.value.split(',').map(function(x){return x.trim()}).filter(Boolean):[]}
  function fillEdit(c){installEditSections();if($('ep-special'))$('ep-special').value=c.special||'';if($('ep-hobby'))$('ep-hobby').value=c.hobby||'';if($('ep-keywords'))$('ep-keywords').value=arr(c.keywords).join(', ');if($('ep-likes'))$('ep-likes').value=arr(c.likes).join(', ');if($('ep-hates'))$('ep-hates').value=arr(c.hates).join(', ');if($('ep-items'))$('ep-items').value=arr(c.items).join(', ');if($('ep-stat-rows')){$('ep-stat-rows').innerHTML='';arr(c.stats).forEach(function(s){addStatRow(s.k,s.v)})}if($('ep-dialogue-rows')){$('ep-dialogue-rows').innerHTML='';arr(c.dialogue).forEach(function(n){addDialogueRow(n)})}try{var raw=localStorage.getItem('lh_line_voice_volume');var v=raw==null||raw===''?0.85:Math.min(1,Math.max(0,Number(raw)||0.85));var range=$('lh-line-voice-vol-range');var label=document.querySelector('#ep-line-voice-vol .lh-line-voice-vol-panel__val');var pct=Math.round(v*100);if(range)range.value=String(pct);if(label)label.textContent=pct+'%'}catch(e){}}
  var oldEdit=window.openEditPanel;
  window.openEditPanel=function(){oldEdit();setTimeout(function(){if(window.currentChar)fillEdit(window.currentChar)},0)};

  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ensureStage);else ensureStage();
})();
